# -------- This file is automatically generated by LSST's sconsUtils -------- #
__version__ = 'unknown'
__repo_version__ = 'unknown'
__fingerprint__ = '79df75d490b786b6e01d6b2b957cb0c79cadfcbb *'
__dependency_versions__ = {
    'python': 'unknown',
}
__all__ = (
    '__version__',
    '__repo_version__',
    '__fingerprint__',
    '__dependency_versions__',
)
